### ISSUE TITLE
Fullscreen slideshow mode

### ISSUE THREAD

**Issue by RigacciOrg** [danboid/shufti#3]
Hi Dan!
I think that your "shufti" is very near what I'm searching for! I wish to have a slideshow program which will present my images collections zoomed and panned as required. This is because I wish to watch my 4:3 photos on my 16:9 screen, and I prefer to have them zoomed into, rather than having black side bands.
So I think that I can add three simple features (command line options) to your program: start already in full-screen mode, get a directory name to display all the images into, and get a timeout parameter to automatically move to the next image.
Are you interested in these features? Can I fork and try to add them? Do you have any suggestion in adding code to your work?
I have also another wish: to add a Ken Burns effect for each displayed image. I imagine to store two pan/zoom states for each image: the initial pan/zoom and the final one, whereas the static image display is a special case where initial and final states are identical. This will require to add two hotkeys: one to store initial state and the other to store the final state...

**Comment by danboid** [comment]
I'm not entirely sure what you mean by adding an option to "get a directory name to display all the images into" - shufti already lets you specify the directory to browse on the command line so that mustn't be what you mean? Having a timeout between images would be a nice optional feature.

Full screen mode is a bit flakey in shufti as it stands - you often have to go in and out of full screen mode to fix the panning but I was never really too concerned about that as I didn't really design it for viewing images full screen, it was created for viewing images windowed, positioned, sized and zoomed/rotated but if you can get it to behave better in full screen mode then great!

Adding the Ken Burns effect thing sounds like it could be tricky and I would have no use for that personally.

The only thing I really wanted to add to shufti was an easy to install/use Mac package but I'm not really a Mac user (although I have owned them in the past and installed Hackintoshes) and no-one seemed to know how to create an easy to install pyqt package for macOS using cx_freeze, not even its developer, so I gave up.

**Comment by RigacciOrg** [comment]
The "directory" option I suggest is because I frist launched "shufti ." to browse the current directory (it did not work because it is a directory name), then I launched "shufti my_image.jpg" and the directory browsing did not worked (because there was no directory part in the name). I just think that the most intuitive way to start a slideshow is to pass a directory name.
I will do some tests starting directly in full-screen mode and doing image auto-next.

**Comment by danboid** [comment]
@RigacciOrg I updated shufti yesterday for the first time in a year so you can now configure the slideshow delay from the command line.

**Comment by danboid** [comment]
I'm closing this because I will probably remove full screen mode from shufti next time I update it. It doesn't really make sense to have a full screen mode IMO.
